[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lidarpf"
version = "0.1.0"
description = "High-performance LiDAR particle filter localization for robotics (Numba-optimized)"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.21",
    "numba>=0.55",
    "pytest",
    "datashader"
]

[project.urls]
Homepage = "https://github.com/yourusername/lidarpf"

[dependency-groups]
dev = [
    "ruff>=0.12.0",
    "ty>=0.0.1a10",
]

[tool.ruff]
line-length = 100
